# Generated by Django 6.0.4 on 2026-05-09 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Дата изменения"),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="views_count",
            field=models.IntegerField(default=0, verbose_name="Количество просмотров"),
        ),
    ]
