# Generated by Django 6.0.4 on 2026-05-04 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactInfo",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("country", models.CharField(default="USA", max_length=50, verbose_name="Страна")),
                ("TIN", models.CharField(default="91-1144442", max_length=12, verbose_name="ИНН")),
                ("address", models.CharField(default="Redmond, WA, 98052-6399", max_length=300, verbose_name="Адрес")),
            ],
            options={
                "verbose_name": "контактная информация",
                "verbose_name_plural": "контактная информация",
            },
        ),
    ]
