# Generated by Django 6.0.4 on 2026-05-20 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0007_product_is_published"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["price"],
                "permissions": [("can_unpublish_product", "Can unpublish product")],
                "verbose_name": "товар",
                "verbose_name_plural": "товары",
            },
        ),
    ]
